### ISSUE TITLE
Great repo

### ISSUE THREAD

**Issue by tuanha2000vn** [matt8707/hass-config#1]
Is there any installation guide in detail?

This is a great project, thank you. Rated Star.

**Comment by matt8707** [comment]
Everything is documented. It is a config, not a theme or an integration. Take the pieces you like!

**Comment by poudenes** [comment]
Its complicated to understand. But Step bij step you will understand how this great peace of code is created... Smart use of yaml code :D

**Comment by cismarine** [comment]
Looks really good!
Thanks for sharing.
