### ISSUE TITLE
question

### ISSUE THREAD

**Issue by gbdavidx** [matt8707/hass-config#10]
how do you get your card to "pop out" like this?  
![image](https://user-images.githubusercontent.com/26369204/82696664-50647680-9c1c-11ea-9580-90d4a6ceeb2d.png)

**Comment by matt8707** [comment]
[/popup/sidebar_information.yaml](https://github.com/matt8707/hass-config/blob/master/popup/sidebar_information.yaml)

* [browser_mod](https://github.com/thomasloven/hass-browser_mod) - popup
* [layout-card](https://github.com/thomasloven/lovelace-layout-card) - side by side
