### ISSUE TITLE
Cannot get UniFi Sensors get working

### ISSUE THREAD

**Issue by clipse2004** [matt8707/hass-config#102]
Hello,

I would need your help for the UniFi sensors, in the router_unifi. yaml were so far no adjustments needed.

In the secrets I have of course defined the IP, password etc.
I just don’t get any values, always “unknown. ”
Do you use a regular Dream Machine or a Pro?
Did I forget anything? A local account in the Dream Machine should be enough or not?

The following error is thrown to me:

`Logger: homeassistant.components.command_line
Source: components/command_line/__init__.py:48
Integration: command_line ([documentation](https://www.home-assistant.io/integrations/command_line), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+command_line%22))
First occurred: 13:14:40 (1 occurrences)
Last logged: 13:14:40

Command failed (with return code 1): python3 << EOF import json, yaml, requests from datetime import datetime from urllib3 import disable_warnings disable_warnings() SECRETS_FILE = "/config/secrets.yaml" def get_secret(secret): try: with open(SECRETS_FILE, "r", encoding="utf8") as file: secrets = yaml.full_load(file) for key, value in secrets.items(): if key == secret: return value except FileNotFoundError: print("secrets.yaml not found") exit() IP = get_secret("unifi_ip") PORT = get_secret("unifi_port") USER = get_secret("unifi_user") PASS = get_secret("unifi_pass") URL = f"https://{IP}:{PORT}" login = requests.request("POST", f"{URL}/api/auth/login", \ headers={"Content-Type": "application/json"}, \ data=json.dumps({"username": USER, "password": PASS}), verify=False) response = requests.request("GET", f"{URL}/proxy/network/api/s/default/stat/device/", \ cookies=login.cookies, verify=False) data = response.json()["data"][0] print(json.dumps({ "cpu": data["system-stats"]["cpu"], "cpu_temp": round(data["temperatures"][1]["value"], 1), "mem": data["system-stats"]["mem"], "disk": round(data["storage"][1]["used"] / data["storage"][1]["size"] * 100, 1), "internet": data["internet"], "uptime": datetime.fromtimestamp(data["startup_timestamp"]).isoformat(), "version": data["displayable_version"] })) EOF`

i hope you can help me

big thanks!

**Comment by matt8707** [comment]
https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/3672

**Comment by clipse2004** [comment]
Um, I’m not sure what you’re trying to tell me.
I just tried this command in the HA Terminal:

`data='{"username":"user","password":"pass"}'; ip='https://192.168.1.1:443'; c=$(curl -H 'Content-Type: application/json' -d $data -ksc - $ip/api/auth/login -o /dev/null); echo "${c}" | curl -ksb - $ip/proxy/network/api/s/default/stat/device/`

Works wonderfully (filled with the correct values of course), then I get a json result.
Now I have in the sensor times omitted the secrets and entered the values directly like this:

`      python3 << EOF
      import json, yaml, requests
      from datetime import datetime
      from urllib3 import disable_warnings
      disable_warnings()

      IP = 'ip of UDM'
      PORT = '443'
      USER = 'My Username'
      PASS = 'My Password'
      URL = f"https://{IP}:{PORT}"

      login = requests.request("POST", f"{URL}/api/auth/login", \
          headers={"Content-Type": "application/json"}, \
          data=json.dumps({"username": USER, "password": PASS}), verify=False)
      response = requests.request("GET", f"{URL}/proxy/network/api/s/default/stat/device/", \
          cookies=login.cookies, verify=False)
      data = response.json()["data"][0]
      
      print(json.dumps({
          "cpu": data["system-stats"]["cpu"],
          "cpu_temp": round(data["temperatures"][1]["value"], 1),
          "mem": data["system-stats"]["mem"],
          "disk": round(data["storage"][1]["used"] / data["storage"][1]["size"] * 100, 1),
          "internet": data["internet"],
          "uptime": datetime.fromtimestamp(data["startup_timestamp"]).isoformat(),
          "version": data["displayable_version"]
      }))
      EOF`

But then I get the same result again, I’m really confused.

`Command failed (with return code 1): python3 << EOF import json, yaml, requests from datetime import datetime from urllib3 import disable_warnings disable_warnings() IP = 'XXXXX' PORT = '443' USER = 'XXXXX' PASS = 'XXXXXXX' URL = f"https://{IP}:{PORT}" login = requests.request("POST", f"{URL}/api/auth/login", \ headers={"Content-Type": "application/json"}, \ data=json.dumps({"username": USER, "password": PASS}), verify=False) response = requests.request("GET", f"{URL}/proxy/network/api/s/default/stat/device/", \ cookies=login.cookies, verify=False) data = response.json()["data"][0] print(json.dumps({ "cpu": data["system-stats"]["cpu"], "cpu_temp": round(data["temperatures"][1]["value"], 1), "mem": data["system-stats"]["mem"], "disk": round(data["storage"][1]["used"] / data["storage"][1]["size"] * 100, 1), "internet": data["internet"], "uptime": datetime.fromtimestamp(data["startup_timestamp"]).isoformat(), "version": data["displayable_version"] })) EOF`

Finally I tried to run the python script with HA Python scripts:

`import json, yaml, requests
from datetime import datetime
from urllib3 import disable_warnings
disable_warnings()

IP = "XXX"
PORT = "443"
USER = "XXX"
PASS = "XXX"
URL = f"https://{IP}:{PORT}"

login = requests.request("POST", f"{URL}/api/auth/login", \
    headers={"Content-Type": "application/json"}, \
    data=json.dumps({"username": USER, "password": PASS}), verify=False)
response = requests.request("GET", f"{URL}/proxy/network/api/s/default/stat/device/", \
    cookies=login.cookies, verify=False)
print(response.json())`

But that then leads to:
`  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
    exec(compiled.code, restricted_globals)
  File "unifi.py", line 2, in <module>
ImportError: __import__ not found`

Unfortunately, I also have no idea about Python:/
I’m really confused now.

**Comment by matt8707** [comment]
Well, you could try what I linked

**Comment by matt8707** [comment]
> Works wonderfully (filled with the correct values of course), then I get a json result.

pm me the output of the curl command and I'll have a look

**Comment by bokkoman** [comment]
I have the exact same problem.
It might be because i own a UDM-SE instead of a UDM-Pro.
Is there any way to figure out how to get this working?

**Comment by matt8707** [comment]
> https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/3672
> 
> https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/3084

**Comment by clipse2004** [comment]
That doesn't help him either... 

Try it without temperature and disk then it works!

**Comment by matt8707** [comment]
It's a lot easier to debug than guess

**Comment by clipse2004** [comment]
I do not guess I know.

**Comment by clipse2004** [comment]
Does the temperature work for you? According to your description, you have a UDM, but I have not yet found inegration etc found, which gives me to the DreamMachine Temp and Disk values.

**Comment by bokkoman** [comment]
> > https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/3672
> > https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/3084

I already tried this.
Searched that forum, then saw the issue here. But you keep linking back to that forum. 
The newer lineup uses a different system. For example, when you login in ssh, you're straight into unifios, no need to give that command to go into unifios.
That makes me believe this night be different too.
But I'm no curl expert, so i can't really debug this. If you want me to test anything, I would be glad to help.

**Comment by bokkoman** [comment]
> Does the temperature work for you? According to your description, you have a UDM, but I have not yet found inegration etc found, which gives me to the DreamMachine Temp and Disk values.

Nothing works for me. I removed the temp and disk part from the code. But no luck. 
Can you perhaps post your working yaml? Then I'll test that.
