### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by Lisu25** [matt8707/hass-config#107]
Hi, after new update HA and update to browser mod 2 i have transparent background on popups and when i add frontend: !include themes.yaml to configuration i cant reset HA. Can you help me?
![Opera Zrzut ekranu_2022-10-15_154839_192 168 50 48](https://user-images.githubusercontent.com/29820892/195990999-ba9afc2c-5b93-46f6-91d9-f13f75915b05.png)
![Opera Zrzut ekranu_2022-10-15_154812_192 168 50 48](https://user-images.githubusercontent.com/29820892/195991001-ea0f1ada-3db2-4a11-b179-faf80abd4d9a.png)

**Comment by souuupl** [comment]
I do have the exact same issue with transparent background after updating to browser mod 2. Can you help me how you solved the issue?

**Comment by EuleMitKeule** [comment]
@Lisu25 Have you found a solution?
