### ISSUE TITLE
darksky

### ISSUE THREAD

**Issue by dwebeklint** [matt8707/hass-config#11]
Hi.

Do you have any replacement weather API for darksky. Its going to shutdown its API.
Service to existing users and subscribers will continue until July 1, 2020

**Comment by CCOSTAN** [comment]
It's actually good until the end of 2021. 
Our API service for existing customers is not changing today, but we will no longer accept new signups. The API will continue to function through the end of 2021.
https://blog.darksky.net/
But NWS is a good replacement if you want to do it sooner.
