### ISSUE TITLE
Assets missing

### ISSUE THREAD

**Issue by Ampersandman** [matt8707/hass-config#113]
Somehow the loader.svg and the background image are not loading properly!

**Comment by matt8707** [comment]
can you access them like this http://...:8123/local/background.png

**Comment by Ampersandman** [comment]
No, but i think it's due to the missing information on what to copy over into the www/ folder.
I found out that the INSTALL.md is missing some crucial information on how to setup i.e. to copy those over and to install lovelace-mushroom for the popups

**Comment by matt8707** [comment]
you're welcome to make a pull request
