### ISSUE TITLE
HA 2022.11 introduces border to cards - theme update required to resolve.

### ISSUE THREAD

**Issue by Harro65** [matt8707/hass-config#118]
With the latest HA 2022.11 release, the title card has introduced a ha-card-border-width: which shows on all cards.

To remove, an update to the theme is needed setting the border width to 0 

Adding the following to the theme looks to resolve.

ha-card-border-width: '0px'

**Comment by matt8707** [comment]
Thanks, but that's already been merged https://github.com/matt8707/hass-config/commit/5314c69fa8e64020dd11c1262e91b0b69c1176f3

**Comment by Xitro01** [comment]
This makes the /config/integrations very ugly, as also the borders there completely dissapear. Isn't there a neater solution to this?

**Comment by matt8707** [comment]
Oh, you're right. I'll reopen this

**Comment by matt8707** [comment]
I think I figured it out → https://github.com/matt8707/hass-config/commit/2699776ef688c9d3358b23a25bf1da28e088dab2

* remove `ha-card-border-width: 0px` from themes.yaml
  borders working again in other sections

* set `border-width: 0` to base.yaml and sidebar.yaml
  this removes all borders from main dashboard

* add `--ha-card-border-width: 0` to `card-mod-more-info` in themes.yaml
  remove all borders in browser_mod popups, but you'll see the borders for a split second

* also add `--ha-card-border-width: 0` to `www/browser_mod_icon.js`
  adds rule even before the popup is loaded

**Comment by Xitro01** [comment]
Just applied your changes and this looks like a much neater solution, thanks alot!

For others, it might be easier to follow these changes to know exactly what you need to change:
https://github.com/matt8707/hass-config/commit/2699776ef688c9d3358b23a25bf1da28e088dab2
