### ISSUE TITLE
Font color for pop-ups is always inverted

### ISSUE THREAD

**Issue by johntdyer** [matt8707/hass-config#119]
So I am trying to figure out how to troubleshoot the fact that all pop-ups for this card are always inverted

<img width="468" alt="image" src="https://user-images.githubusercontent.com/58234/200414920-6e7b4321-260e-43cf-a5fc-477eb0409210.png">

This seemingly only happens for the popups ajnd not for the cards themselves

<img width="600" alt="image" src="https://user-images.githubusercontent.com/58234/200415065-869c310b-731c-4c79-baf1-20be6fcc367e.png">

I am not even sure how best to begin troubleshooting this, hoping you can offer some advice :)

**Comment by matt8707** [comment]
https://github.com/matt8707/hass-config/issues/91
