### ISSUE TITLE
Plex Senor

### ISSUE THREAD

**Issue by gkostakisNemea** [matt8707/hass-config#120]
Hi, 

I'm having problem to setup the plex_recently_added sensor. 
I follow the all the steps and the debug procedure.

first of  all i have installed plex server within homeassistant on Raspberry Pi4

when i hit the follow 
http://192.168.1.10:32400/library/recentlyAdded?X-Plex-Token=******

I get this:
✖Activate License KeyRefreshChecked Sites0Torrent NameStatusQualityLang.0 scanned torrentsLeave feedbackBackEnter your license key and click on the activate button to start using µTorrent Web ProActivateIf you do not have a license key, click on the button below to purchase onePurchase License KeyAllow communication with SoftwaresLeave feedback
<MediaContainer size="0" allowSync="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1661862985" mixedParents="1"> </MediaContainer>

and in development tools i have:

entity: sensor.plex_recently_added
           Plex Recently Added 
state:  Online 
attributes:  data:  
                  friendly_name: Plex Recently Added

**Comment by matt8707** [comment]
Hi, this is not a support forum for plex
