### ISSUE TITLE
REST broken affects version updates

### ISSUE THREAD

**Issue by Xitro01** [matt8707/hass-config#127]
For the people that question why the version pop-up broke after the last update (2022.11.2), this is related to "version_updates.yaml" in the packages folder. This is because the REST integration schema is broken in the last release.

See: https://github.com/home-assistant/core/issues/81812
And the milestone here: https://github.com/home-assistant/core/pull/81857

2022.11.3 will fix this issue!

Before updating to 2022.11.3 when it's released: comment out the "rest" lines in version_updates.yaml -> perform the update -> remove the commenting -> reboot one last time.

**Comment by novisys** [comment]
thta's what i did 👍

**Comment by novisys** [comment]
this one can be also helpful:
https://github.com/home-assistant/core/issues/81812#issuecomment-1308132276

**Comment by matt8707** [comment]
Yeah, but you can't have duplicate yaml keys, so that's not an option. I tried the patch and it still is not working. If .3 doesn't fix this I'll revert to https://www.home-assistant.io/integrations/sensor.rest/

**Comment by matt8707** [comment]
fixed in 2022.11.3
