### ISSUE TITLE
How do I adjust for second tables with smaller resolution ? 

### ISSUE THREAD

**Issue by johntdyer** [matt8707/hass-config#128]
So I have a fire 10 and a fire 7.  The fire 10 looks amazing , love it... but its a bit oversized for the fire 7 and I am wondering how to scale it... your jedi-fu is so strong I am not sure where to begin,... I assume I can use useragent to gate the logic, I'm just not sure where I might "compress" it to support multiple resolutions?

**Comment by matt8707** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries
https://github.com/matt8707/hass-config/blob/b7284de5cc098b4f043c22ffbdba61faea1607f0/ui-lovelace.yaml#L18

**Comment by matt8707** [comment]
with that you can match device width and set a different padding

also here for grid titles
https://github.com/matt8707/hass-config/blob/b7284de5cc098b4f043c22ffbdba61faea1607f0/themes.yaml#L128

**Comment by johntdyer** [comment]
Thanks
