### ISSUE TITLE
Icon Explanation

### ISSUE THREAD

**Issue by damiantje99** [matt8707/hass-config#16]
Hi,

First off all, I want to say what a great setup u have. Its really smooth and looks professional. Amazing!
I was wondering how you got these icons like the fan or the toilet working.

I want to do these animations also with a ceiling light and maybe later with other icons.

Could you explain it to me?

**Comment by matt8707** [comment]
read up https://www.w3schools.com/css/css3_animations.asp
https://github.com/matt8707/hass-config/blob/master/ui-lovelace.yaml

**Comment by damiantje99** [comment]
Awesome, thanks!
