### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by Xitro01** [matt8707/hass-config#165]
Hi Matt,

I also have a Samsung Galaxy Tab A 10.1 (2019), but experience a lot of delays with this dashboard.
It takes about 2-3 seconds when you stand in front before you can do something and also opening pop-ups takes some time.
While the default lovelace dashboard loads almost instantly.

Is there any way to optimize this dashboard so that it loads quicker?

Best regards,
Chris

**Comment by novisys** [comment]
A good idea, but this will take some Time to be 100% user friendly.
Can you explain how you get to relie thé interaction between HA and the dashboard ? 🤔

**Comment by matt8707** [comment]
> A good idea, but this will take some Time to be 100% user friendly.

I've added a raw editor (similar to lovelace)

> Can you explain how you get to relie thé interaction between HA and the dashboard ? 🤔

Using [home-assistant-js-websocket](https://github.com/home-assistant/home-assistant-js-websocket) (same as lovelace)

**Comment by novisys** [comment]
that's what i was thinking !
Thanks for your response 😉

**Comment by Xitro01** [comment]
> Hi! There's really not much that can be done. This config relies on custom cards.
> 
> I have however started working on a custom dashboard (not lovelace) that is crazy fast.
> 
> <img alt="screen" width="2000" src="https://user-images.githubusercontent.com/36163594/221669159-7e226f38-a9d1-4933-a5c6-b3cfec90b3d0.png">
> 
> but I'm really busy so progress is slow

Will it have this look, or something similar to what you made earlier?

**Comment by matt8707** [comment]
this is just a prototype I haven't started thinking about design yet

**Comment by Xitro01** [comment]
My current dashboard scores 14 in Performance by the way.
These are the recommendations, mostly related to JS files being loaded:
![Knipsel](https://user-images.githubusercontent.com/19844787/222669122-0012e347-3970-4351-a2d1-5e9d494f92dc.PNG)

Is there something that I can do right now with the current dashboard to speed things up, like minify/compress current JS files and only load JS files when they're actually being used?

**Comment by Xitro01** [comment]
Quite curious on what your progression is so far on the new dashboard. :) Care to share anything with us?
Thanks!
