### ISSUE TITLE
hello, can you help me please?

### ISSUE THREAD

**Issue by roh735** [matt8707/hass-config#17]
i have problem with hass_dev_release, i connect it like this on sensor.yaml
and its always unknown

I don't use docker, any idea why its not working? because other your scrips working
Please let me know if you can help, thank you
see attached

image

      hass_dev_release:
        icon_template: mdi:dev-to
        friendly_name_template: >
          {% if ((as_timestamp(state_attr('calendar.home_assistant_devs', 
          'start_time')) - as_timestamp(states.sensor.time.last_changed | as_local)) / 86400) > 20 %}
            Planerad beta
          {% else %}
            {{ state_attr('calendar.home_assistant_devs','message') }}
          {% endif %}
        value_template: >
          {% set dev = ((as_timestamp(state_attr('calendar.home_assistant_devs', 
          'start_time')) - as_timestamp(states.sensor.time.last_changed | as_local)) / 86400) %}
          {% if dev < -1 %} Released
          {% elif dev < 0 %} Today
          {% elif dev < 1 %} Tomorrow
          {% elif dev > 20 %} No
          {% else %} {{ dev | int + 1 }} days
          {% endif %}

**Comment by roh735** [comment]
i have problem with hass_dev_release, i connect it like this on sensor.yaml
and its always unknown

I don't use docker, any idea why its not working? because other your scrips working
Please let me know if you can help, thank you
see attached

![image](https://user-images.githubusercontent.com/66237408/94597208-e6f01680-0252-11eb-819f-a8bbebbe0785.png)


```
      hass_dev_release:
        icon_template: mdi:dev-to
        friendly_name_template: >
          {% if ((as_timestamp(state_attr('calendar.home_assistant_devs', 
          'start_time')) - as_timestamp(states.sensor.time.last_changed | as_local)) / 86400) > 20 %}
            Planerad beta
          {% else %}
            {{ state_attr('calendar.home_assistant_devs','message') }}
          {% endif %}
        value_template: >
          {% set dev = ((as_timestamp(state_attr('calendar.home_assistant_devs', 
          'start_time')) - as_timestamp(states.sensor.time.last_changed | as_local)) / 86400) %}
          {% if dev < -1 %} Released
          {% elif dev < 0 %} Today
          {% elif dev < 1 %} Tomorrow
          {% elif dev > 20 %} No
          {% else %} {{ dev | int + 1 }} days
          {% endif %}
```

**Comment by matt8707** [comment]
You need to subscribe to the public calendar

https://developers.home-assistant.io/
https://www.home-assistant.io/integrations/calendar.google/

**Comment by roh735** [comment]
connected, now i have this page "media browser".
in states now i have calendar. states but still hass_dev_release didnt change , still unknown, is it anything you can help me? thank you

![image](https://user-images.githubusercontent.com/66237408/94842099-960e2880-03e0-11eb-818c-03342536deca.png)

**Comment by matt8707** [comment]
The template works, either you're targeting the wrong calendar or you didn't set it up properly. The media browser has nothing to do with it.

![cal](https://user-images.githubusercontent.com/36163594/94992845-f5a93700-058c-11eb-993c-98e0c5709756.png)

**Comment by roh735** [comment]
sorry, may be its stupid question but how to set it up like this? because I don't have it

![image](https://user-images.githubusercontent.com/66237408/94994336-93384280-055c-11eb-8a81-c6c2c8317625.png)


its my code

sensor.yaml:

`      hass_dev_release:
        icon_template: mdi:dev-to
        friendly_name_template: >
          {% if ((as_timestamp(state_attr('calendar.home_assistant_devs', 
          'start_time')) - as_timestamp(states.sensor.time.last_changed | as_local)) / 86400) > 20 %}
            Planerad beta
          {% else %}
            {{ state_attr('calendar.home_assistant_devs','message') }}
          {% endif %}
        value_template: >
          {% set dev = ((as_timestamp(state_attr('calendar.home_assistant_devs', 
          'start_time')) - as_timestamp(states.sensor.time.last_changed | as_local)) / 86400) %}
          {% if dev < -1 %} Released
          {% elif dev < 0 %} Today
          {% elif dev < 1 %} Tomorrow
          {% elif dev > 20 %} No
          {% else %} {{ dev | int + 1 }} days
          {% endif %}`

**Comment by matt8707** [comment]
I mean this has nothing to do with my template code, you might want to ask in a relevant thread on the forums

* The template code above works
* You're getting `unknown` state because `start_time` and `message` can't be extracted
* Your only attributes are `offset_reached` and `friendly_name`!
* You need to subscribe to [Upcoming Events](https://developers.home-assistant.io/)
* Click the + to add upcoming dates in your Google Calendar
![cal](https://user-images.githubusercontent.com/36163594/94996620-04e8ae80-05a6-11eb-9280-db9895d0c863.png)
* Connect Google Calendar to Home Assistant using [this guide ](https://www.home-assistant.io/integrations/calendar.google/)

![cal2](https://user-images.githubusercontent.com/36163594/94992845-f5a93700-058c-11eb-993c-98e0c5709756.png)

```yaml
#google_calendars.yaml

- cal_id: p07...@group.calendar.google.com
  entities:
  - device_id: home_assistant_devs
    ignore_availability: true
    name: Home Assistant Devs
    track: true
```

**Comment by roh735** [comment]
thank you so much i was missing Upcoming events in my google calendar  so i just click here '+google kalender' and it fixed

thank you
 
![image](https://user-images.githubusercontent.com/66237408/94997303-d7810e00-056f-11eb-9bba-62ea54b3c54f.png)
