### ISSUE TITLE
Cannot read properties of null (reading'config')

### ISSUE THREAD

**Issue by keppi** [matt8707/hass-config#173]
After Update to Home Assistant 2023.4.0b4 all entities on the Dashboard shows "Cannot read properties of null (reading'config')"

**Comment by mrmultifunk** [comment]
Update to the latest version of button-card and card-mod and you will be (mostly) fine. Also, check out the beta channel on Discord.

**Comment by mrmultifunk** [comment]
I'm not sure if it is related to the beta version, but the youtube watching sensor is no longer working for me. I have it configured as a command-line sensor as shown in your youtube-watching repository.

Another thing i noticed, is there seems to be a black bar in the footer area of the homescreen, after updating the theme.
![image](https://user-images.githubusercontent.com/56545669/229584497-ea0ef593-4158-450d-9170-f5c1b402231e.png)

**Comment by keppi** [comment]
did everything... same Problem

**Comment by matt8707** [comment]
> EDIT: also clear browser cache

**Comment by keppi** [comment]
sorry... my mistake thanks!!

**Comment by matt8707** [comment]
https://github.com/matt8707/hass-config/releases/tag/2023.4
