### ISSUE TITLE
Plex token

### ISSUE THREAD

**Issue by bokkoman** [matt8707/hass-config#178]
I've been using the theme for almost a year now.
I also use the Plex recently added card. For that you need a Plex Token.
Which, according to the docs, you grab from the info xml. Like described here:
https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

Which is fine, but it is not a permanent token. See the green section on that page.

So my question or maybe feature request is, to use a permanent token. As described here:
https://forums.plex.tv/t/authenticating-with-plex/609370

Thank you

**Comment by Gibletron** [comment]
@bokkoman this repository is about a dashboard frontend, not about the specific plex-recently-added integration / component that you are referring.
The component repository can be found here: https://github.com/NemesisRE/sensor.plex_recently_added
However, NemesisRE is not activly developing the component, as such if you want to see the change in this world, you've got to be the change in this world :)

**Comment by matt8707** [comment]
I've never had to update my plex token (years), so it's def long-lived 👍
