### ISSUE TITLE
Theme popup transparency not working on ipadOS  

### ISSUE THREAD

**Issue by Polster85** [matt8707/hass-config#179]
Within my installation it seems that the provided tablet.yaml file works correctly in a chrome based solution (browser for example). But I face some issues on the IPadOS (IOS 15.x) with the companion app, because it is using the Safari browser to service Home Assistant.

Within the companion app as well the safari browser itself the transparency on all popups are not working. After some research I found the 'backdrop-filter' only with works with the '-webkit-' prefix (https://www.w3schools.com/cssref/css3_pr_backdrop-filter.php).

I couldn't make it work yet, maybe you know where to add all the required '-webkit-' prefixes to get it functional.

**Comment by kolsbjerg0055** [comment]
Im also having this issue :-(

**Comment by matt8707** [comment]
https://github.com/matt8707/hass-config/blob/0c7f0d0b210e46729d8d9e58a9005f7646f9b51a/themes/tablet.yaml#L126

the webkit prefix is in ha frontend

https://github.com/home-assistant/frontend/blob/6d1ea414492a3a9530ddcb1ba805919816e67f29/src/components/ha-dialog.ts#L76-L77

i can confirm it works on ios (iphone)

**Comment by gergelyz** [comment]
> https://github.com/matt8707/hass-config/blob/0c7f0d0b210e46729d8d9e58a9005f7646f9b51a/themes/tablet.yaml#L126
> 
> the webkit prefix is in ha frontend
> 
> https://github.com/home-assistant/frontend/blob/6d1ea414492a3a9530ddcb1ba805919816e67f29/src/components/ha-dialog.ts#L76-L77
> 
> i can confirm it works on ios (iphone)

Thanks Mattias.
I can confirm the same config works fine on my iPhone (iOS) also but experiencing the issue above on my iPad (iPadOS).
Do you have any potential resolution to this or it seems more like a HA related problem?
Thanks

**Comment by matt8707** [comment]
I just tried ipados 16.4 in xcode simulator, and it works. so I'd bet it's something on your end

**Comment by kolsbjerg0055** [comment]
> https://github.com/matt8707/hass-config/blob/0c7f0d0b210e46729d8d9e58a9005f7646f9b51a/themes/tablet.yaml#L126
> 
> the webkit prefix is in ha frontend
> 
> https://github.com/home-assistant/frontend/blob/6d1ea414492a3a9530ddcb1ba805919816e67f29/src/components/ha-dialog.ts#L76-L77
> 
> i can confirm it works on ios (iphone)

How do I update this? - Sorry, pretty new to HASS

**Comment by matt8707** [comment]
There's nothing to update. I just showed that the code for safari is already present

**Comment by Polster85** [comment]
Hi, same here. Works perfect on iPhone (latest iOS) but on the iPad (older model; iOS 15.x) it doesn’t. Can you try the Xcode simulator on iOS 15? Just to make sure it is not an issue based on older Safari versions?

**Comment by matt8707** [comment]
<img width="1143" alt="ios15" src="https://github.com/matt8707/hass-config/assets/36163594/f6e6cccb-d970-4063-9ee1-6dc77688e6f7">

**Comment by gergelyz** [comment]
![screenshot](https://github.com/matt8707/hass-config/assets/74494989/e761b994-950e-4f96-bdea-dc536f90872f)
Not sure how much it helps in debugging but I noticed the following odd behaviour also.
If I turn my iPad's screen off from my PC using browser mod, the buttons still remain visible.
The native popups of HomeAssistant work perfectly though

**Comment by gergelyz** [comment]
I have re-downloaded the whole button_card_templates directory and that fixed my issue!

**Comment by Polster85** [comment]
Yes same here! 

When I diff the previous yaml files, tilt.yaml has a change where this seems fixed:

`    tilt_enable: >
      [[[
        // disable on macos app, text appears over popup
        if (window.navigator.userAgent.includes("Home Assistant")) {
            return false
        }
        // enable on macos browsers
        else if (window.navigator.userAgent.match(/Macintosh; Intel Mac OS X/i)) {
            return true;
        }
        // default - phones, tablets etc
        return false;
      ]]]`
