### ISSUE TITLE
How to add jellyfin to this front-end framework?

### ISSUE THREAD

**Issue by stevenliuit** [matt8707/hass-config#180]
Hello:
I see that ha supports the addition of jellyfin_ha, but I don’t know how to replace the configuration in plex to use this plugin
Plug-in address:https://github.com/koying/jellyfin_ha
Because jellyfin is open source and free, I hope you can adapt it.

**Comment by matt8707** [comment]
I've found that Plex is better at identifying media and plex doesn't cost a anything unless you opt in for the extra features, so it works for me.

I read that it jellyfin_ha "Supports the "upcoming-media-card" custom card" so you should just be a drop in replacement if the data structure is the same

thanks for the suggestion, though.

**Comment by cnewman402** [comment]
I have upcoming-media-card working with Emby.  Jellyfin is a spinoff of Emby anyway.

**Comment by stevenliuit** [comment]
thank you
