### ISSUE TITLE
There are adjustments about the button card lock

### ISSUE THREAD

**Issue by luckhy2882** [matt8707/hass-config#192]
Hello experts
I want to add a lock on the button to prevent the power from being accidentally pressed. How to modify the program, thank you.
For example: long press or right key to lock, unlock the same way

          - type: custom:button-card
            entity: switch.gosund_fan_switch
            name: "Fläkt\u00B2"
            template:
              - base
              - icon_fan2
              - loader
              - lock
            variables:
              lock: >
                [[[
                  let lock = states['input_boolean.imac_lock'];
                  return !lock || lock.state;
                ]]]
              trigger: >
                [[[
                  let trigger = states['script.home_leave'];
                  return !trigger || trigger;
                ]]]
![LOCK](https://github.com/matt8707/hass-config/assets/125120787/c0b0967c-b473-4690-8f65-9544431280cf)

**Comment by matt8707** [comment]
[https://github.com/matt8707/hass-config/blob/master/packages/computer_imac.yaml#L17-L37](https://github.com/matt8707/hass-config/blob/1dd8a3b441555799596abfdaa6f12db6188ca60b/packages/computer_imac.yaml#L17-L37)

Here is what's blocking the switch from toggling if `input_boolean.imac_lock` is on. The button-card template is for icon and animations

**Comment by luckhy2882** [comment]
> matt8707
Thanks for matt8707's reply. I want to change the fan to a button lock to prevent the fan from turning off when pressed accidentally. I want to design a double-press lock and hold to unlock. I don't know how to modify it. I'm sorry for the trouble. Thank you.
