### ISSUE TITLE
Restarting after update to yaml

### ISSUE THREAD

**Issue by ericlindersson** [matt8707/hass-config#193]
Is there a better way than to restart the whole system to make changes to the yaml files take effect?
Just reloading yaml doesn't seem to make the updates visible.

**Comment by matt8707** [comment]
if you mean the dashboard, then any change to ui-lovelace is enough. i'm using https://github.com/akmolina28/lovelace-gulp-watch which does that automatically

**Comment by robsonke** [comment]
I struggled with this as well and just added a simple shell command to my "refresh everything" script:
```
shell_command:
    refresh_lovelace: "touch /config/dashboards/main-dashboard.yaml"
```
