### ISSUE TITLE
Wallpanel Full Screen

### ISSUE THREAD

**Issue by tekwreck** [matt8707/hass-config#194]
Not sure how this could be related, I'm using chromium kiosk mode with wall panel full screen. For some reason after following your install steps your stuff works fine however I can't seem to enable wall panel now.

**Comment by matt8707** [comment]
Isn't this an issue with "wall panel"?

**Comment by tekwreck** [comment]
So I figured it out, copying the changes on your install guide for the modules eliminates any existing modules enabled via HACS. I had to manually add wallpanel's resource into the configuration yaml in addition to all the other modules I had installed via HACS.
