### ISSUE TITLE
2023.7 workaround

### ISSUE THREAD

**Issue by h3nrytan** [matt8707/hass-config#195]
Hello Matt,

Just wondering, does the patch browser_mod break your custom:button-card in vacuum popup?

**Comment by matt8707** [comment]
Hi, not that I know of, but button-cards inside popups broke if you patched and then updated browser_mod so try this https://github.com/matt8707/hass-config/releases/tag/2023.9

**Comment by h3nrytan** [comment]
Hey Matt,

All good with the latest release!

Thanks!
