### ISSUE TITLE
Can't edit the dashboard cards.

### ISSUE THREAD

**Issue by tunavis** [matt8707/hass-config#198]
Receiving the following error when clicking on edit: The edit UI is not available when in YAML mode.

**Comment by bckthomas** [comment]
Take a look here : https://community.home-assistant.io/t/the-edit-ui-is-not-available-when-in-yaml-mode/370290/5

**Comment by hebval** [comment]
I get this message too. I was able to edit it at first, and now I comeback an hour later and I can't edit it.

**Comment by matt8707** [comment]
that's just how dashboards works
https://www.home-assistant.io/dashboards/dashboards/

**Comment by ductu3590** [comment]
Please elaborate on how to fix this problem.
