### ISSUE TITLE
Popup is transparent on iPad

### ISSUE THREAD

**Issue by kolsbjerg0055** [matt8707/hass-config#199]
Im experience a strange issue with popup which are transparent, it works just fine using safari browser on Mac.

Home assistant: 2023.10.1

![IMG_5682](https://github.com/matt8707/hass-config/assets/72004104/7c3aded3-2fcf-4da2-b103-122444a49deb)

How to solve this?

**Comment by matt8707** [comment]
https://github.com/matt8707/hass-config/commit/34011e1f37e4b1e98c6e2bc66316e180c17bdafb
