### ISSUE TITLE
light-slider-card

### ISSUE THREAD

**Issue by septeven** [matt8707/hass-config#2]
Hi,
First, great setup, I love it.

I tried to implement some ideas of your setup into mine but I'm encountering some issue with the custom light-slider-card. I downloaded it from your github because I was unable to find it elsewhere - is it a custom element that you developed by yourself ?

Anyway, for now, this is totally unusable with an iPhone (probably the same with an iPad) since when trying to shifting the slider, it scrolls the page behind the popup instead of controlling the slider.

Also, I would love to be able to customize it a little bit - any chance you tell me more about this custom element ?

Thanks

**Comment by matt8707** [comment]
Hey, 

https://github.com/matt8707/hass-config#lights-and-sensors
> Modified (CSS+JS) vertical [Light Entity Card](https://github.com/ljmerza/light-entity-card) for easier touch control.

https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/35?u=mattias_persson

I'm aware that it's not working on mobile but I'm only using it with a tablet and desktop. I may look into it sometime.
