### ISSUE TITLE
Person pop up card not showing 

### ISSUE THREAD

**Issue by 1ntroduc3** [matt8707/hass-config#20]
Using the pop-up card for who's home and not is not showing details anymore (no wifi Bluetooth device tracker map information anymore) since around 13 November. 
![5372ce08408ab8535463787f98bf6388e5a8dfe6](https://user-images.githubusercontent.com/36326262/99352726-6d17f900-28a3-11eb-92da-2b971945f0c4.png)
![f4fb2d559b06b14c0934f2c17e8ed4669a8274a0](https://user-images.githubusercontent.com/36326262/99352742-7012e980-28a3-11eb-97b7-4062390b166a.png)

**Comment by matt8707** [comment]
downgrade stack-in-card 0.2.0 -> 0.1.1
