### ISSUE TITLE
Showing Camera in Sidebar?

### ISSUE THREAD

**Issue by Itsie** [matt8707/hass-config#203]
Hello Matt,
thank you for the wonderful design, it is very difficult for me to understand since here everything only goes through the ui-lovelace.yaml and not anymore in the frontend.

But I also want to get into it, however, my wife would like to have a camera (Netatmo) displayed, can it be put in the sidebar as the live image? I tried it on the dashboard itself, but there it is just a small box and not like, for example, with media. Maybe it could replace the 4 tiles at Hemma and include the presence of my family in the sidebar. Do you have an idea? Can I buy you a beer?

I would be very grateful for your help ;)

**Comment by tnusch** [comment]
At the end of the day the sidebar is also made out of button-cards (https://github.com/custom-cards/button-card). 
Button cards have the entity_picture option to show pictures/images instead of icons and/or text on the button card. 

Hope this helps!

**Comment by Itsie** [comment]
Hey @tnusch ,

thank you for that, but where should i put the Card in ?

**Comment by tnusch** [comment]
Everything goes into ui-lovelace.yaml, regardless if you choose to replace the 4 tiles in the main dashboard (e.g. hemma section) or the sidebar. The ui-lovelace.yaml file is grouped into the corresponding sections (sidebar, media etc) which you can individually change.

**Comment by Itsie** [comment]
<img width="1460" alt="image" src="https://github.com/matt8707/hass-config/assets/21281203/42fd3054-a4bb-4cd0-a981-9b6514d836c3">

Hey tnusch, first of all, thank you for that. I just have the problem that it is displayed so small and I don't know how to fix it.

I have created a camera.yaml as a template, the content is:
`camera:
  template:
    - settings
  show_icon: false
  show_name: false
  show_state: false
  show_label: false
  show_entity_picture: true
  show_live_stream: true
  tap_action:
    action: more-info
  styles:
    card:
      - background: transparent
      - border-radius: 12px
      - box-shadow: none
      - width: 100%
      - height: auto
`

Unfortunately, it is displayed very small and not centered, as shown in the picture. Even in the dashboard itself, I tried, but I always encounter the problem with the size. And the frame in the background.

Do you perhaps have a tip for me?
