### ISSUE TITLE
Where are the Fonts

### ISSUE THREAD

**Issue by briglx** [matt8707/hass-config#22]
You reference SF Text and several other fonts but I don't see them in your repo. Where do you find them and where do you install them to be picked up?

**Comment by matt8707** [comment]
The san francisco font is not free and I can't include it for copyright reasons, but if you were to google it, In www/font.css you can see that the fonts are placed in www/font.

**Comment by stevmills** [comment]
I was able to get the fonts from [Apple](https://developer.apple.com/fonts/) directly. Only slight modifications to the `font.css` file necessary.
