### ISSUE TITLE
some problem about the tab A

### ISSUE THREAD

**Issue by anschein** [matt8707/hass-config#24]
HI,I got the same tab A,but there is a problem with WIFI.
Every time I closed the screen a little minutes and the WIFI Automatic shutdown and the Fully kiosk will reload the page.
sorry to ask but with this pad how do i prevent the WIFI sleep?I`m treid every settings in system and in the fully kiosk.  not work
Or I can only keep the screen on?

**Comment by matt8707** [comment]
I keep the screen on all the time, using fullykiosk screensaver. Faster ”wake-up” time too. That may solve it?

**Comment by anschein** [comment]
Thanks for advise,I change the settings and use fullykiosk to manage screen.problem solved.
And what`s the faster"wake-up" time?

**Comment by matt8707** [comment]
Cool! I mean using the screensaver has a faster response time than powering on the screen from off.
