### ISSUE TITLE
Missing entitie device_tracker.lukas (or mattias in your Config)

### ISSUE THREAD

**Issue by SEMPL3X** [matt8707/hass-config#25]
Hello

First of all: what a damn beautiful design !! I love it.

Now the fucking part. I don't know if I'm too stupid or something, but I miss the device_tracker.lukas. How is it made? After hours of research I have to annoy you: /. Excuse the circumstances. 

Have a great week and Thanks in advance
Lukas

**Comment by SEMPL3X** [comment]
Thank you very much, but where is it in your build? I can't find where, for example, are you creating device_tracker.mattias?

**Comment by matt8707** [comment]
https://github.com/matt8707/hass-config/blob/18a268c4df9cb758ca042ad50467c16260165925/configuration.yaml#L76

**Comment by SEMPL3X** [comment]
Many thanks :) Keep on going :)
