### ISSUE TITLE
markdown/html issues with the theme

### ISSUE THREAD

**Issue by KaoruKanon** [matt8707/hass-config#26]
Hi @matt8707,

Since the recent update of frontend and integrations of hacs, i have added your newest code to my hass config. 

I got your last themes.yaml to my config. The tablet theme is activated

I have cleared the cache, force reload the website. Nothing really happens

![issue1](https://user-images.githubusercontent.com/40307380/109489818-b3c2e500-7a87-11eb-97ac-d971f3a385b2.PNG)

![issue2](https://user-images.githubusercontent.com/40307380/109489872-c50bf180-7a87-11eb-8773-cf681039a59c.PNG)

![issue 3](https://user-images.githubusercontent.com/40307380/109489657-7a8a7500-7a87-11eb-87d6-9c34ef464aac.PNG)

**Comment by matt8707** [comment]
Sup,
It’s because of the breaking changes in card-mod 3. I’ll push something this week.

**Comment by KaoruKanon** [comment]
I remain attentive

**Comment by matt8707** [comment]
https://github.com/matt8707/hass-config/commits/master
