### ISSUE TITLE
synologydsm_baseoid

### ISSUE THREAD

**Issue by georgbachmann** [matt8707/hass-config#3]
I LOVE your UI! Looks awesome!
I started rebuilding some of your components and one is the Synology-DSM-Info-Panel.
I saw that you use `synologydsm_baseoid` in the runtime (Drifttid) sensor... could you tell me what that is? I couldn't figure it out yet ;)
Have a great day,
Cheers,
Georg

**Comment by matt8707** [comment]
**DSM**

> Control Panel > Terminal & SNMP > Enable SNMP Service
> Tick SNMPv1, SNMPv2c service.
> Community: public
> Click Apply


configuration.yaml
```
sensor:
  - platform: snmp
    host: !secret synologydsm_host
    community: public
    name: Drifttid
    baseoid: 1.3.6.1.2.1.25.1.1.0
    value_template: >
      {% set uptime = value %}
      {% set days = ((uptime | int) / 8640000) | int %}
      {% set hours = ((uptime | int) / 360000) | int %}
      {% set minutes = ((uptime | int) / 6000) | int %}
      {% if days >= 2 %}{{ days }} dagar
      {% elif days >= 1 %}{{ days }} dag
      {% elif minutes < 1 %}Mindre än 1 minut
      {% elif minutes <= 1 %}{{ minutes }} minut
      {% elif minutes < 60 %}{{ minutes }} minuter
      {% elif hours <= 1 %}{{ hours }} timme
      {% elif hours < 24 %}{{ hours }} timmar
      {% endif %}
```

If the baseoid doesn't work google "synology snmpwalk"

**Comment by georgbachmann** [comment]
Awesome! That did work! Thanks a lot!
