### ISSUE TITLE
Smaller display (Fire Tablet 7) and template issue

### ISSUE THREAD

**Issue by jnpetersen** [matt8707/hass-config#34]
Hello!  Thanks for putting this dashboard together, it gives me some ideas for mine.  I'm having 2 issues with what I'm using from your setup.

1) The buttons are huge on my little display, so I can only fit 8 buttons on screen before I have to scroll.  Where would I change the sizing so that the buttons would decrease in size to make more items visible?

2) I'm using the template.yaml file, when I first loaded the file I got the data I needed, but after I restarted home assistant for other updates, the template is now blank and the state shows unavailable.

Any help would be greatly appreciated.

**Comment by jnpetersen** [comment]
Here is a screenshot of how I see things on a smaller screen.  I'd like to make them smaller.

![image](https://user-images.githubusercontent.com/963185/121104905-d7e53f00-c7b7-11eb-8681-7e60c686a3dd.png)

**Comment by jnpetersen** [comment]
I figured out the template issue, I had changed something and was missing a single quote at the end of the entity name.  Through off all other templates.

Still needing help with the sizing of the boxes, but I think I may have found where to look, in the the button_card_templates section.

**Comment by matt8707** [comment]
Hi, they fill the available space in that grid area. ui-lovelace / https://grid.layoutit.com/
add more columns or increase the grid gap with `custom-layout-card-padding` in themes.yaml

**Comment by Backslashh** [comment]
hey @matt8707, Sorry to hijack this thread but I have a similar issue and I was wondering if you could point me in the right direction of where to look.

My sidebar isn't working as I expect it to. In mobile view, the text is too small, and in desktop view, the padding is really off so the sidebar doesn't look right.

Are you able to help me with where I should be looking to adjust these? I haven't made any modifications to the themes.yaml or the button templates so not sure why it's all weird.

![image](https://user-images.githubusercontent.com/2252680/121456929-2ed25a80-c9ea-11eb-9ecb-a6122e11afd4.png)

![image](https://user-images.githubusercontent.com/2252680/121456999-4c9fbf80-c9ea-11eb-88fb-a538d8d8c915.png)

**Comment by matt8707** [comment]
[#1309](https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/1309?u=mattias_persson)

[#1319](https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/1319?u=mattias_persson)

**Comment by Backslashh** [comment]
Thanks for the update.
So I need to remove the footer markdown styling in themes.yaml if I don't want to use a footer?
this bit:
```
#################################################
        #                                               #
        #           CORONAVIRUS MARKDOWN CARD           #
        #                                               #
        #################################################

        "grid-layout$hui-markdown-card:last-of-type$":
          .: |
            ha-card, ha-markdown {
              background: none;
              padding: 0 !important;
              pointer-events: none;
              margin-top: -1vw;
            }

            ha-markdown {
              overflow: hidden;
            }

          ha-card>ha-markdown$: |
            ha-markdown-element {
              opacity: 0.6;
              font-size: 1.26vw;
              font-weight: 400;
              --mdc-icon-size: 1.2vw;
              font-family: SF Display;
              letter-spacing: 0.05vw;
              line-height: 0px;
              white-space: nowrap;
            }

            ha-icon {
              vertical-align: 3%;
              opacity: 0.4;
            }

            /* phone */
            @media screen and (max-width: 800px) {
              ha-markdown-element {
                display: none;
              }
            }
```

**Comment by Backslashh** [comment]
That's perfect.
Thank you.
