### ISSUE TITLE
All the other components in Zip

### ISSUE THREAD

**Issue by remirr** [matt8707/hass-config#35]
Hi there, 

I am relatively new to HA and I was wondering if you could answer my question. I have copied the contents of the custom_components folder to my HA config under custom_components. What about all the other folders and files? 

Do I not need these? Where should these go? 

Once I have copied the folder to custom_components, do I need to do anything else? 

Thanks!

**Comment by matt8707** [comment]
`www/community` & `custom_components` = [hacs](https://hacs.xyz/)
`configuration.yaml` & `include` = [configuration](https://www.home-assistant.io/docs/configuration/)
`ui-lovelace.yaml` & `popup` = [dashboard](https://www.home-assistant.io/lovelace/)

**Comment by remirr** [comment]
Thanks a lot - so am I editing the configuration.yaml in my HA instance and manually adding your code from your configuration.yaml and include to my configuration.yaml

For the www/community & custom components... am I getting that from hacs? because I looked for your name on hacs but nothing came back...

<img width="1782" alt="Screen Shot 2021-06-11 at 19 34 28" src="https://user-images.githubusercontent.com/2309583/121757586-0fbbf180-caec-11eb-9c9f-b8b93bb15629.png">


for Dashboard and lovelace... same

Sorry if this is really basic, I am trying to learn!

**Comment by matt8707** [comment]
> Sorry if this is really basic, I am trying to learn!

Please read the documentation, that's what it's for
https://www.home-assistant.io/docs/

> For the www/community & custom components... am I getting that from hacs?

Yes


> because I looked for your name on hacs but nothing came back...

because I didn't code www/community & custom components, I installed those from hacs.

**Comment by remirr** [comment]
So I have searched for all the components under HACS and none are coming up... Why cant I just copy the folders from your Zip to my HA folder I browse to in SAMBA?

<img width="793" alt="Screen Shot 2021-06-18 at 12 47 45" src="https://user-images.githubusercontent.com/2309583/122593373-919fa380-d033-11eb-84f3-460bc77b863e.png">
