### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by JorgeAnzola** [matt8707/hass-config#36]
Not an issue, just wanted to say that this is basically the most awesome HA dashboard on the entire vast internet.
Thanks for sharing it! I basically just want to copy it over.

**Comment by stevmills** [comment]
I have to say I feel the same!! I've only just started integrating, but already it looks so good! Thank you!

![hass](https://user-images.githubusercontent.com/4315440/126436544-62efa459-6349-49ec-9fe8-b1fa7a4c3bc0.PNG)

**Comment by JorgeAnzola** [comment]
Hey, at least you're further in the process 😂 
![Screenshot 2021-07-21 at 09 03 41](https://user-images.githubusercontent.com/15676614/126445949-57b1fc65-1587-4693-9e0d-30fddab141c0.jpg)

**Comment by JorgeAnzola** [comment]
> I have to say I feel the same!! I've only just started integrating, but already it looks so good! Thank you!
> 
> ![hass](https://user-images.githubusercontent.com/4315440/126436544-62efa459-6349-49ec-9fe8-b1fa7a4c3bc0.PNG)

Hey @stevmills, would you mind sharing your code? (Or parts of it), I'm struggling a lot adapting the theme to my instance. my email is jorgeanzola@gmail.com

@matt8707 Sorry for doing that on the issue, but Stev didn't have a repo I could comment on.
