### ISSUE TITLE
Square cropped in sliders

### ISSUE THREAD

**Issue by themaluxis** [matt8707/hass-config#37]
Hey man,

thanks for your share, your lovelace is awesome :)
But  I have a problem with it, squares in slider cards are cropped, have you any idea of how to fix it ?
https://i.imgur.com/aO7zSwP.jpg

Thanks

**Comment by matt8707** [comment]
**Known issues**
* swipe-card not updating size unless resizing window [#32](https://github.com/bramkragten/swipe-card/issues/32) [#147](https://github.com/thomasloven/lovelace-layout-card/issues/147)

**Comment by themaluxis** [comment]
> **Known issues**
> 
> * swipe-card not updating size unless resizing window [#32](https://github.com/bramkragten/swipe-card/issues/32) [#147](https://github.com/thomasloven/lovelace-layout-card/issues/147)

There is no fix possible ? Even playing with windows size, square still cropped :-/
Using YAML or GUI mode, same problem

**Comment by matt8707** [comment]
okay, I found something, in `themes.yaml` change `grid-card-gap: 5%` to `1.1vw`

<img src="https://user-images.githubusercontent.com/36163594/130536650-9cf5a5dd-d659-424a-bbfd-2cd5c4ae0657.png" width="50%">

<img src="https://user-images.githubusercontent.com/36163594/130536669-88906561-3806-4c4c-903d-a2db8441c66a.png" width="50%">

**Comment by themaluxis** [comment]
It works great ! :)

**Comment by FishCoding** [comment]
If the change that @matt8707 said does not affect to his current setup probably would be better to introduce it in master.
