### ISSUE TITLE
Request - svg icons

### ISSUE THREAD

**Issue by abonforti** [matt8707/hass-config#46]
Where do you pick svg icons? I would like to add some more!

**Comment by matt8707** [comment]
I made them in illustrator

**Comment by abonforti** [comment]
Alright, may I ask you if you have some spare time to make one "generic button"? I would love to use that for some input boolean components!

**Comment by matt8707** [comment]
I don't but you can follow this https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/264

**Comment by abonforti** [comment]
Lovely, thanks!
