### ISSUE TITLE
Dynamic Grid column count with mediaquery?

### ISSUE THREAD

**Issue by simaovienna** [matt8707/hass-config#49]
I'm trying to change the layout for the mobile view to get "Övrigt" over the full screen width with 3 or 4 tiles . Is there a way to set the grid columns from 2 to 1 only for devices with _max-width: 800px_ (with media query)?

```
      # - type: grid
        # title: Övrigt
        # view_layout:
          # grid-area: övrigt
        # columns: 2
        # cards:
```

Thanks!

**Comment by matt8707** [comment]
grid card doesn't support media queries

use layout-card 

https://github.com/matt8707/hass-config/blob/master/popup/sidebar_vacuum.yaml#L73-L87
