### ISSUE TITLE
file path on lovelace config

### ISSUE THREAD

**Issue by xilense** [matt8707/hass-config#5]
i got question about [ui-lovelace.yaml](https://github.com/matt8707/hass-config/blob/2b54f82acb82aef972971ff537be14299b823b40/ui-lovelace.yaml#L5) , is it refer to this [bar-card.js](https://github.com/matt8707/hass-config/blob/master/www/community/bar-card/bar-card.js)

but that 2 files is on different path 
on lovelace it says `/community_plugin/bar-card/bar-card.js`
but the file actually on `/community/bar-card/bar-card.js`

did i just miss something or will hass recognize it?

i'm still bit confused how to implement your config to mine , what needed to copy and what to not

i just amazed by the time i saw your ui on forum, that's so nice ui
Thank you for sharing your config!

**Comment by matt8707** [comment]
Yeah, the paths are correct. I'm not sure why they're implemented that way.
