### ISSUE TITLE
Roborock Vacuum Map - Icon of vacuum and charging unit

### ISSUE THREAD

**Issue by Xitro01** [matt8707/hass-config#55]
Hi Mattias,

How did you get the icons, for the vacuum and charging unit, like this:
![Knipsel](https://user-images.githubusercontent.com/19844787/151780823-c2a8dba3-e026-4f7e-a24f-cd6d77d614ff.PNG)

This is not in your configuration and it seems that it's not implemented by Xiaomi-Cloud-Map-Extractor yet.

Hope you can help.
Thanks in advance!

**Comment by matt8707** [comment]
Hello, that was a different card when I used valetudo, I just haven't updated the screenshots in a while...

<img width="220" alt="1" src="https://user-images.githubusercontent.com/36163594/152693844-9faf4d32-30f7-4d6c-966e-1010f16123f7.png">
