### ISSUE TITLE
Combine custom:button-card with custom:slider-button-card

### ISSUE THREAD

**Issue by simaovienna** [matt8707/hass-config#56]
Hi,

is it possible to integrate the custom:slider-button-card and combine it with the custom:button-card to use templates, etc.?

https://github.com/mattieha/slider-button-card

thanks!

**Comment by matt8707** [comment]
Hi, maybe, but I'd imagine it would be hard because of button-card tap action interfering with the slider

**Comment by bckthomas** [comment]
I tried but without result :(

**Comment by simaovienna** [comment]
Thanks for your replies. Thomas, would you mind to share your approach?

cheers

**Comment by bckthomas** [comment]
Sorry but it was few months ago, I don't remember my approach
