### ISSUE TITLE
in "/config/_button_card_templates.yml", line 1167, column 9: Unable to read file /config/.youtube_token.txt.

### ISSUE THREAD

**Issue by PalmTamino** [matt8707/hass-config#58]
![grafik](https://user-images.githubusercontent.com/36358673/159563655-f217c51d-a97e-435e-a6e9-cd1bd5affedb.png)

**Comment by PalmTamino** [comment]
![grafik](https://user-images.githubusercontent.com/36358673/159563904-5f7613fd-9f75-4157-8d41-94d5368e3ac6.png)

**Comment by Backslashh** [comment]
So this requires that you have a .youtube_token.txt file in your HA root directory.
If you don't have that, this error will occur.

**Comment by PalmTamino** [comment]
> So this requires that you have a .youtube_token.txt file in your HA root directory.
> If you don't have that, this error will occur.

Not mentioned in the guide… And what should i put in this file?

**Comment by matt8707** [comment]
[https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/2887](https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/2887)
