### ISSUE TITLE
Update of button state in popup

### ISSUE THREAD

**Issue by THorst92** [matt8707/hass-config#61]
Hi Matt,

I really love your config and it is already set up as my default dashboard. Thanks for sharing!!
I have one question concerning custom buttons in popups. I have the Roborock S7 and want to control the mop settings via buttons. Therefore I‘ve changed also for the fan speed the select-entity into a button row:
Here an example for the fan-speed „Off“ and „Silent“:

    - type: horizontal-stack
           cards:
          
            - type: custom:button-card
              icon: mdi:fan-off
              state:
                - operator: template
                  value: >
                    [[[
                      return states['sensor.vacuum_fan_speed'].state == "105"
                    ]]]
                  color: '#4e7ea3'
                - operator: default
                  color: '#9da0a2'
              tap_action:
                action: call-service
                service: vacuum.send_command
                service_data:
                  entity_id: vacuum.roborock_s7
                  command: set_custom_mode
                  params: [105]
              template: icon_only_small

            - type: custom:button-card
              icon: mdi:fan-alert
              state:
                - operator: template
                  value: >
                    [[[
                      return states['sensor.vacuum_fan_speed'].state == "Silent"
                    ]]]
                  color: '#4e7ea3'
                - operator: default
                  color: '#9da0a2'
              tap_action:
                action: call-service
                service: vacuum.send_command
                service_data:
                  entity_id: vacuum.roborock_s7
                  command: set_custom_mode
                  params: [101]
              template: icon_only_small 

And a screenshot:
![6D5880A8-4480-4AC5-8175-608F6A02C621](https://user-images.githubusercontent.com/22470970/164990921-c605fe99-d5bd-4e16-bb07-2d868b291155.jpeg)

Remark: The template icon_only_small is a copy of the template icon_only with a reduced size of the button.

I now have the problem, that if I press a button for another speed, the state of the button does not get updated. Only if I close and reopen the popup, the state is updated.
Do you have an idea how I can fix this? This would be great!

Best regards,

Thorsten

**Comment by matt8707** [comment]
Hi, it's been discussed, take a look here
https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/2863

**Comment by matt8707** [comment]
`{{ "#4e7ea3" if is_state('sensor.vacuum_fan_speed', '105') else "#9da0a2" }};`

**Comment by THorst92** [comment]
Thanks for your response! 
I found another issue which caused also the problem. I had to remove the "default" color-definition in the template.
Now it works.

Thank you so much for your help!
