### ISSUE TITLE
Question about tablet mount

### ISSUE THREAD

**Issue by MarvinSchenkel** [matt8707/hass-config#62]
Hey Matt,

I am currently looking to buy a tablet and wallmount. The one you linked in your README looks really nice and minimal. I was just wondering, how have you managed the power and how does this look on your wall? Would you mind sharing some pictures of the end-result, I'm really curious :-).

Cheers,
Marvin

**Comment by matt8707** [comment]
Hi, nothing special :sweat_smile:. I've routed a long power cable behind the mirror, down to a wall socket. I have to mention two things they stated on their website though:

_"The holder’s low-key design enables unobtrusive, flat wall mounting"_
it's not flush, from wall to tablet is 5cm (2 inches)

_"Easy insertion and removal of the tablet"_
yeah, if you're two people, one to pull apart the holders and one to pry out the tablet

![hall](https://user-images.githubusercontent.com/36163594/166103964-9b7ab871-409c-41cc-8b14-72995a09d1e9.jpg)

**Comment by MarvinSchenkel** [comment]
Thanks a lot for this. I am planning to drill a hole in the wall and use a 90 degree angled cable to power the tablet. Would that fit with this tablet holder?

**Comment by matt8707** [comment]
idk, holder variable fit = 7" to 13" and tablet dimensions =  9.65" x 5.88"
so I think it has to be mounted like the image, and that may block a 90 degree cable

![charge](https://user-images.githubusercontent.com/36163594/166146880-fc035bf4-e14b-439d-99ab-31a9cacf0269.jpg)

**Comment by MarvinSchenkel** [comment]
I think they mean "You can use this mount with any tablets from size 7" up until 13"", so you could probably mount the holders at the top and the bottom of the tablet. That would make it possible to use a 90 degree cable without any issue I guess?


![](https://assets.durable.eu/dam/media/11/11426/5044/preview_image/standard/8933_23_APP_D.jpg)

**Comment by matt8707** [comment]
Yes, but what I was trying to convey is that 7 > 5.88. 

In my case, the tablet is smaller than the mount if you align the holders vertically.

**Comment by MarvinSchenkel** [comment]
That's really deceiving since their product page makes it look like they are talking about the screen diagonal that has to measure between 7" and 13" , not the dimensions of the tablet:

![](https://assets.durable.eu/dam/media/11/11548/5166/original_1560x1560/free/8933_23_ILL_A.jpg)

**Comment by matt8707** [comment]
Ah, I see what you're saying. The marketing is misleading. But they do at least list "Symmetrical opening" under "Product description".

**Comment by MarvinSchenkel** [comment]
Fair enough, thanks for the heads up and all the information. I think I a gonna buy a Galaxy Tab A8 along with this mount :-)
