### ISSUE TITLE
Unifi OS  Sensor

### ISSUE THREAD

**Issue by to4ko** [matt8707/hass-config#64]
Hi!

Could you please share your unifi OS sensor (command itself)? Got nothing on this in google :(

Thanks!

**Comment by matt8707** [comment]
hello

post https://community.home-assistant.io/t/cookie-login-to-get-value-for-sensor/350417/9

troubleshoot https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/3084

**Comment by to4ko** [comment]
Thanks!!!

**Comment by to4ko** [comment]
Hi @matt8707 !

Could you please share reboot and power commands?

unifi_poweroff: !secret unifi_poweroff
unifi_reboot: !secret unifi_reboot

I'm using UDM PRO and sometime Network Controller hangs and  only reboot helps
