### ISSUE TITLE
Splitting up Button Card Templates

### ISSUE THREAD

**Issue by shbatm** [matt8707/hass-config#65]
Hi! Just want to first say thank you for sharing all your work and customizations, I have borrowed quite a bit for my own install.

I wanted to share something back since it looks like it might fit your organization style. Not sure if you know already, but I recently found out that you can split up button card templates into separate files under one folder. The following works inside `ui-lovelace.yaml` like it does inside `configuration.yaml`:

```yaml
button_card_templates: !include_dir_merge_named button-card-templates/
```

```shell
config/
├─ button-card-templates/
│  ├─ sidebar.yaml
│  ├─ icons.yaml
│  ├─ popups.yaml
```

**Comment by matt8707** [comment]
Hello. I've thought about it. I don't like having too many files, but I agree that splitting it up somewhat is a good idea!

**Comment by shbatm** [comment]
Normally agree, mine had just grown to the point I got tired of scrolling searching for the right template. Just wanted to make sure you knew the option!
