### ISSUE TITLE
Editable Button Labels

### ISSUE THREAD

**Issue by laz3rpenguin** [matt8707/hass-config#7]
Hi Mattias,

Love this config, it's really awesome. Would it be possible for you to supply (an) un-flattened, document form template/s/ for us to create our own labels, preferably as a Photoshop document, or whatever you used to create these originally.

I tried to edit some of these using Photoshop, however I could not quite get close to the level of design work you have achieved here.

Many thanks.

**Comment by matt8707** [comment]
I recently transitioned to svg's which made the buttons 80% smaller and loads noticeably faster on my tablet. So the **exact** process for this is:

- Install [Illustrator](https://www.adobe.com/se/products/illustrator/) and [SF Pro font](https://developer.apple.com/fonts/).

- Download this archive https://drive.google.com/open?id=1goft1VcdMdK1YHeUgVEZnB_NNQc90-LM

- You're able to edit the text and you can paste in you own icon. You can even copy the icons [from my repository](https://github.com/matt8707/hass-config/tree/master/www/btn) and paste in place with exact position with ⌘F.

- You can leave the text editable but to make the svg scale well you need to apply **Object > Expand** on the font so it makes the text into shapes.

- Then throw it into [nano](https://vecta.io/nano) to additionally reduce the file size by approximately 30%.

[This](https://github.com/matt8707/hass-config/blob/master/www/uibg.png) is the background which is compressed to 24x15px and the browser scales it smoothly to full viewport.

That's it.

**Comment by TheAmitMa** [comment]
Thanks.
I looked into it too.

What about the "Fade Effect"?

**Comment by matt8707** [comment]
Scratch that. I'm rewriting every button so you can edit text. Will push soon. 

What fade effect?

**Comment by TheAmitMa** [comment]
When you toggle button from on to off, it have some kind of effect that change the color from white to black. The same as with "off to on" of course...

**Comment by matt8707** [comment]
@laz3rpenguin I updated ui-lovelace to use button card instead, with inline svg icons and animations.

**Comment by laz3rpenguin** [comment]
Thank you. I ended up creating custom SVGs for most of my buttons and still in the process of doing so, which makes it easier. 

I was messing around and ended up making like a climate icon which seems to suit the style of the rest of the icons. I can PR this if you want, not really anything too special, just thought if there is anyone out there needing one for a climate entity, then they can use it...

**Comment by matt8707** [comment]
Yeah, do it. Here's more info https://community.home-assistant.io/t/lovelace-button-card/65981/3396?u=mattias_persson
