### ISSUE TITLE
Secret imac_off not defined 

### ISSUE THREAD

**Issue by wisonlau** [matt8707/hass-config#76]
The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: Secret imac_off not defined

```
Home Assistant 2022.8.6
Supervisor 2022.08.3
Operating System 7.6
version： 20220802.0 - latest
```

Do you need to configure anything else?

**Comment by matt8707** [comment]
don't copy packages

https://github.com/matt8707/hass-config/blob/master/INSTALL.md
