### ISSUE TITLE
Browser_mod 2.0

### ISSUE THREAD

**Issue by S1M8N** [matt8707/hass-config#81]
Hello matt,

With the new browser mod version the code is not similar, can you help me to change old code with the new code ? 

Because in my case it's dosen't work qith the new code...

Thanks you very much

Simon

**Comment by novisys** [comment]
there some modifications to put in différent files to addapt this config to the new BM 2.0
I also had the same problem, i retrograde from 2.0 to 1.5 at this time…
Waiting for matt or others contributors for the best solution, i try to do it but with few/no success at my side

**Comment by matt8707** [comment]
https://github.com/matt8707/hass-config/releases/tag/2022.9
