### ISSUE TITLE
pupups doesnt work

### ISSUE THREAD

**Issue by vejbuch** [matt8707/hass-config#82]
Hi,
They don't pop up for me but I followed the instructions but they still don't work. Anyone have any idea why?

![image](https://user-images.githubusercontent.com/6008834/188489022-9316e1c0-c181-4cec-8f42-197693e9a698.png)

**Comment by matt8707** [comment]
https://github.com/matt8707/hass-config/releases/tag/2022.9

https://github.com/matt8707/hass-config/commits?author=matt8707&since=2022-08-31&until=2022-09-05
