### ISSUE TITLE
Secret unifi_network not defined

### ISSUE THREAD

**Issue by dannyvfilms** [matt8707/hass-config#83]
Followed [INSTALL.md](https://github.com/matt8707/hass-config/blob/2022.9/INSTALL.md) to get started. On reboot my main Dashboard says "Secret unifi_network not defined" with the option to Reload UI.

Since the guide didn't take me this far, I poked around and found `unifi_network` in [secrets_redacted.yaml](https://github.com/matt8707/hass-config/blob/2022.9/secrets_redacted.yaml) and added that to my config folder. I then updated `unifi_ip`, `unifi_user`, `unifi_pass`, `unifi_network`, and `unifi_console`. Restarting does not fix the issue. 

[configuration.yaml.zip](https://github.com/matt8707/hass-config/files/9501085/configuration.yaml.zip)

**Comment by dannyvfilms** [comment]
That definitely got me to a bootable dashboard, but now I wish [INSTALL.md](https://github.com/matt8707/hass-config/blob/2022.9/INSTALL.md) went **much** further on configuration instructions. This definitely shows how new I am to custom Home Assistant dashboards, but I haven't a clue how to change the language, let alone make some of the neat stuff shown. Adding additional steps to the guide would be much appreciated.

**Comment by matt8707** [comment]
Great! I won't spend time writing documentation, it already exists for each component. You are welcome to contribute to INSTALL.md 👍🏻
