### ISSUE TITLE
Vacuum map card map mode selection causes popup to close

### ISSUE THREAD

**Issue by ocelot2123** [matt8707/hass-config#84]
In the map mode selection drop down of the vacuum map card in footer_vacuum.yaml, when I click the dropdown and then click anywhere else it automatically closes the entire vacuum popup which makes it kinda unusable. Not sure if this is something I misconfigured on my end or if there is any fix for this, any help would be appreciated, thanks in advance!

![image](https://user-images.githubusercontent.com/15928184/188815463-eb947328-cd4c-4af1-813c-46fe98306dae.png)

**Comment by Xitro01** [comment]
Known issue: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/398

**Comment by Xitro01** [comment]
@matt8707 Yeah been tracking that issue for a while now. Good that it’s solved. Waiting for the official release. Still loving the dashboard by the way. Awesome job!

**Comment by ocelot2123** [comment]
awesome, thanks guys! I think I will wait for the official release then. Really loving the dashboard so far 👍
