### ISSUE TITLE
more-info popup close browser_mod popup

### ISSUE THREAD

**Issue by S1M8N** [matt8707/hass-config#87]
Hello,

When I click on an entity to display "more info" (example: history), the popup below disappears. I would prefer that the popup stacks...

Can we skirt this?

Thanks for your help

https://i.imgur.com/oz5436i.png
https://i.imgur.com/b6wQObu.png

**Comment by matt8707** [comment]
Hi. It doesn't really bother me. Have you tried [ignore_popup_card](https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md#browser_modmore_info)? 

Otherwise create an issue https://github.com/thomasloven/hass-browser_mod/issues
