### ISSUE TITLE
INSTALL.md instructions + ui-lovelace.yaml Missing Property title

### ISSUE THREAD

**Issue by temstet1234** [matt8707/hass-config#88]
Hi,
I hope I did well and copy files to the right location according to what written in the INSTALL.md instructions.

"Manually copy over these files from [matt8707/hass-config](https://github.com/matt8707/hass-config)

ui-lovelace.yaml
button_card_templates folder
popup folder
themes.yaml
sidebar.yaml
"
Now I get in the ui-lovelace.ymal Errors:
Missing property "title".
Incorrect type. Expected "string".
Property layout is not allows.

Please your help! :-)

![Screenshot 2022-09-17 132815](https://user-images.githubusercontent.com/113381888/190852258-16e67424-afaa-4201-996d-2ee97267b5ed.jpg)

**Comment by matt8707** [comment]
it's the [vs code extension](https://marketplace.visualstudio.com/items?itemName=keesschollaart.vscode-home-assistant) config validation, I think this will remove the warnings https://github.com/matt8707/hass-config/commit/d8dc05c157ce2196efad3fb869c796a6e5db734f
