### ISSUE TITLE
Black text on popup cards 

### ISSUE THREAD

**Issue by johntdyer** [matt8707/hass-config#91]
The text on the pop ups is black and doesnt appear to be using the same front... Any clue why it wouldnt be white like the main board?   Where is this controlled at ?

**Comment by matt8707** [comment]
Can you post a screenshot?

**Comment by johntdyer** [comment]
![image](https://user-images.githubusercontent.com/58234/193580011-20eecf7f-0aab-40e8-a8d9-79819659df82.png)

![image](https://user-images.githubusercontent.com/58234/193580064-15918d81-8924-468f-9f67-cd2d739ae699.png)

**Comment by matt8707** [comment]
select dark mode

[![Open your Home Assistant instance and show your Home Assistant user's profile.](https://my.home-assistant.io/badges/profile.svg)](https://my.home-assistant.io/redirect/profile/)

**Comment by johntdyer** [comment]
ah, awesome ! I had it on Auto.. now it works.. Did I miss that step in the readme?
