### ISSUE TITLE
Swipe card + Brightness control

### ISSUE THREAD

**Issue by Xitro01** [matt8707/hass-config#93]
Hi Matt,

As the entities of my Home Assistant begin to grow and grow, I think it would be nice to create more swiper cards (like what you did with Media). And then put less used/less important entities on the second page.

I made something for my lamps now, but the problem is that I can't control the brightness via the circle anymore.

As you are really clever in these kind of solutions: do you maybe know a solution to this?

Thanks in advance!

**Comment by FunkeyFlo** [comment]
This seems to do the trick: https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/3692

**Comment by Xitro01** [comment]
> This seems to do the trick: https://community.home-assistant.io/t/a-different-take-on-designing-a-lovelace-ui/162594/3692

Awesome, that worked, thanks alot!
