### ISSUE TITLE
No theme available

### ISSUE THREAD

**Issue by Baggerfahrer** [matt8707/hass-config#96]
Hey,

i tried to install the theme yesterday and i sticked to every point mentioned in the manual explained [here](https://github.com/matt8707/hass-config/blob/master/INSTALL.md) but i cannot select any different theme....

See here:
![grafik](https://user-images.githubusercontent.com/25987294/194691799-648ce17b-2217-403c-bf66-0140d80af937.png)

The ui states that i should select the tablet ui, but obviously i cannot...

![grafik](https://user-images.githubusercontent.com/25987294/194691947-2d65dd9d-f82b-483f-af1a-b568aee0ac45.png)

Any ideas what im doing wrong?

**Comment by matt8707** [comment]
* themes.yaml in root config folder
* `frontend: !include themes.yaml` in configuration.yaml
* check home-assistant.log

**Comment by Baggerfahrer** [comment]
thanks for your reply!!

i have absolutely no clue what i changed now, but your test theme worked like a charm..... i started newly over again, and now it seems to work.

can be closed, many thanks
